import type { ReactNode } from 'react';
import { Amita, Geist, Geist_Mono, Urbanist } from "next/font/google";
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { ThemeProvider } from 'next-themes';

import NavigationBar from '@/app/(delete-this-and-modify-page.tsx)/NavigationBar';
import '@/app/globals.css';
import { Toaster } from '@/registry/new-york-v4/ui/sonner';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900'
});
const getAmita = Amita({
  variable: "--font-amita",
  subsets: ["devanagari"],
  weight: "400", // or "700" depending on your preference
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        // ? https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app
        // ? https://react.dev/reference/react-dom/client/hydrateRoot#suppressing-unavoidable-hydration-mismatch-errors
        <html suppressHydrationWarning lang='en'>
            <body
               className={`${geistSans.variable} ${getAmita.variable} bg-ship text-foreground overscroll-none antialiased`}>
                <ThemeProvider attribute='class'>
                    {/* <NavigationBar /> */}
                    {children}
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    );
};

export default Layout;
