import type { ReactNode } from 'react';
import { Amita, Rubik, Urbanist } from "next/font/google";
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { ThemeProvider } from 'next-themes';

import NavigationBar from '@/app/(delete-this-and-modify-page.tsx)/NavigationBar';
import '@/app/globals.css';
import { Toaster } from '@/registry/new-york-v4/ui/sonner';
import { ReactFlowProvider } from '@xyflow/react';
import ShaderBackground from '@/components/Drishti/chat/shader';

const getRubik = Rubik({
    variable: "--font-rubik",
    subsets: ["latin"], // You can add more subsets like 'latin-ext', 'cyrillic', etc.
    weight: ["400", "700"], // You can include multiple weights
});
const getUrbanist = Urbanist({
    variable: "--font-urbanist",
    subsets: ["latin"], // You can add more subsets like 'latin-ext', 'cyrillic', etc.
    weight: ["600", "500", "400", "900"], // You can include multiple weights
});

const getAmita = Amita({
    variable: "--font-amita",
    subsets: ["devanagari"],
    weight: "400", // or "700" depending on your preference
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        // ? https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app
        // ? https://react.dev/reference/react-dom/client/hydrateRoot#suppressing-unavoidable-hydration-mismatch-errors
        <html suppressHydrationWarning lang='en'>
            <body
                className={`${getAmita.variable} ${getUrbanist.variable}  text-foreground overscroll-none antialiased`}
                style={{ fontFamily: 'var(--font-urbanist) !important' }} >
                <ReactFlowProvider>
                    <ThemeProvider attribute='class'>
                        {/* <NavigationBar /> */}
                        <ShaderBackground />
                        {children}
                        <Toaster />
                    </ThemeProvider>
                </ReactFlowProvider>
            </body>
        </html>
    );
};

export default Layout;
