import type { ReactNode } from 'react';
import type { Metadata } from 'next';

import { ThemeProvider } from 'next-themes';
import '@/app/globals.css';
import { Toaster } from '@/registry/new-york-v4/ui/sonner';
import { ReactFlowProvider } from '@xyflow/react';
import ShaderBackground from '@/components/Drishti/chat/shader';
import AuthProvider from '@/providers/AuthProvider';
import InactivityProvider from '@/components/admin/InactivityProvider';

const getRubik = {
    variable: "--font-rubik",
};
const getUrbanist = {
    variable: "--font-urbanist",
};
const getAmita = {
    variable: "--font-amita",
};

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        <html suppressHydrationWarning lang='en'>
            <body
                className={`${getAmita.variable} ${getUrbanist.variable} text-foreground overscroll-none antialiased`}
                style={{ fontFamily: 'var(--font-urbanist) !important' }}
            >
                <ReactFlowProvider>
                    <AuthProvider>
                        <ThemeProvider attribute='class'>
                            <ShaderBackground />
                            {children}
                            <Toaster />
                            {/* Inactivity tracker — covers all authenticated routes */}
                            <InactivityProvider />
                        </ThemeProvider>
                    </AuthProvider>
                </ReactFlowProvider>
            </body>
        </html>
    );
};

export default Layout;