import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import React from 'react';

interface Answer {
  question: string;
  answer: string;
}

interface TableRow {
  equipment: string;
  assembly: string;
  recommendation: string;
  shipName?: string;
}

interface RCMReportPDFProps {
  shipName: string;
  equipmentNames: string[];
  tableRows: TableRow[];
  answers: Answer[];
  generatedDate: string;
  generatedTime: string;
}

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottom: '2 solid #0891b2',
    paddingBottom: 15,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#0f172a',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#64748b',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#334155',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  infoBox: {
    backgroundColor: '#f1f5f9',
    padding: 15,
    borderRadius: 4,
    marginBottom: 15,
  },
  infoLabel: {
    fontSize: 10,
    color: '#64748b',
    marginBottom: 4,
  },
  infoValue: {
    fontSize: 14,
    color: '#0f172a',
    fontWeight: 'bold',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#0891b2',
    padding: 10,
  },
  tableHeaderCell: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#ffffff',
    flex: 1,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: '1 solid #e2e8f0',
    padding: 10,
  },
  tableCell: {
    fontSize: 10,
    color: '#334155',
    flex: 1,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 9,
    color: '#94a3b8',
    borderTop: '1 solid #e2e8f0',
    paddingTop: 10,
  },
});

export const RCMReportPDF: React.FC<RCMReportPDFProps> = ({
  shipName,
  equipmentNames,
  tableRows,
  answers,
  generatedDate,
  generatedTime,
}) => {
  // Multi-ship detection based on actual rows
  const isMultiShip =
    tableRows.map(r => r.shipName).filter(Boolean).length > 1;

  return (
    <Document>
      <Page size="A4" style={styles.page}>

        {/* HEADER */}
        <View style={styles.header}>
          <Text style={styles.title}>RCM Analysis Report</Text>
          <Text style={styles.subtitle}>
            Generated on {generatedDate} at {generatedTime}
          </Text>
        </View>

        {/* SHIP INFO */}
        <View style={styles.section}>
          <View style={styles.infoBox}>
            <Text style={styles.infoLabel}>SHIP</Text>
            <Text style={styles.infoValue}>{shipName}</Text>
          </View>
          <View style={styles.infoBox}>
            <Text style={styles.infoLabel}>EQUIPMENT SELECTED</Text>
            <Text style={styles.infoValue}>
              {equipmentNames.join(', ')}
            </Text>
          </View>
        </View>

        {/* TABLE */}
        <Text style={styles.sectionTitle}>Maintenance Policy</Text>

        <View style={styles.tableHeader}>
          <Text style={styles.tableHeaderCell}>Equipment</Text>
          {isMultiShip && (
            <Text style={styles.tableHeaderCell}>Ship</Text>
          )}
          <Text style={styles.tableHeaderCell}>Nomenclature</Text>
          <Text style={styles.tableHeaderCell}>Maintenance Policy</Text>
        </View>

        {tableRows.map((row, index) => (
          <View key={index} style={styles.tableRow}>
            <Text style={styles.tableCell}>{row.equipment}</Text>
            {isMultiShip && (
              <Text style={styles.tableCell}>
                {row.shipName || 'Unknown Ship'}
              </Text>
            )}
            <Text style={styles.tableCell}>{row.assembly}</Text>
            <Text style={styles.tableCell}>{row.recommendation}</Text>
          </View>
        ))}

        <Text style={styles.footer}>
          This report was automatically generated by the RCM Analysis System.
        </Text>

      </Page>
    </Document>
  );
};