"""create reliability tables clean

Revision ID: 2370969d316a
Revises: d062f35ad603
Create Date: 2026-02-12 16:02:09.109955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '2370969d316a'
down_revision: Union[str, Sequence[str], None] = 'd062f35ad603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchman_statistics',
    sa.Column('stat_id', sa.Uuid(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('syncs_triggered', sa.Integer(), nullable=False),
    sa.Column('syncs_skipped', sa.Integer(), nullable=False),
    sa.Column('false_positives', sa.Integer(), nullable=False),
    sa.Column('avg_check_duration_ms', sa.Float(), nullable=True),
    sa.Column('total_time_saved_seconds', sa.Integer(), nullable=False),
    sa.Column('total_rows_synced', sa.Integer(), nullable=False),
    sa.Column('skip_rate_percent', sa.Float(), nullable=True),
    sa.Column('accuracy_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('stat_id')
    )
    op.create_index(op.f('ix_watchman_statistics_stat_date'), 'watchman_statistics', ['stat_date'], unique=False)
    op.create_table('alphabeta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etabeta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('eta', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etl_execution_progress',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('job_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_table('etl_execution_logs',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('log_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['etl_execution_progress.execution_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('watchman_audit_log',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('check_timestamp', sa.DateTime(), nullable=False),
    sa.Column('needs_sync', sa.Boolean(), nullable=False),
    sa.Column('decision_reason', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('source_row_count', sa.Integer(), nullable=True),
    sa.Column('target_row_count', sa.Integer(), nullable=True),
    sa.Column('changed_rows_count', sa.Integer(), nullable=True),
    sa.Column('source_watermark', sa.DateTime(), nullable=True),
    sa.Column('check_duration_ms', sa.Integer(), nullable=True),
    sa.Column('job_queued', sa.Boolean(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['etl_execution_progress.execution_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.add_column('etl_schedule', sa.Column('etl_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('etl_schedule', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('etl_schedule', sa.Column('current_execution_id', sa.Uuid(), nullable=True))
    op.add_column(
        'etl_schedule',
        sa.Column(
            'cancellation_requested',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('0')
        )
    )
    op.add_column('etl_schedule', sa.Column('last_trigger_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('etl_schedule', sa.Column('source_watermark', sa.DateTime(), nullable=True))
    op.add_column('etl_schedule', sa.Column('target_watermark', sa.DateTime(), nullable=True))
    op.add_column('etl_schedule', sa.Column('rows_changed_since_last_check', sa.Integer(), nullable=True))
    op.add_column('etl_schedule', sa.Column('last_change_detected', sa.DateTime(), nullable=True))
    op.add_column(
    'etl_schedule',
    sa.Column(
        'sync_risk_score',
        sa.Integer(),
        nullable=False,
        server_default=sa.text('0')
    )
)

    op.add_column('etl_schedule', sa.Column('last_sync_start', sa.DateTime(), nullable=True))
    op.add_column('etl_schedule', sa.Column('last_sync_duration_seconds', sa.Integer(), nullable=True))

    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('SUPERUSER', 'ADMIN', 'USER', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPERUSER', 'ADMIN', 'USER', name='userrole'),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('system_configuration', 'system_id',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               nullable=True)
    op.alter_column('rcm', 'rcm_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.VARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_column('etl_schedule', 'last_sync_duration_seconds')
    op.drop_column('etl_schedule', 'last_sync_start')
    op.drop_column('etl_schedule', 'sync_risk_score')
    op.drop_column('etl_schedule', 'last_change_detected')
    op.drop_column('etl_schedule', 'rows_changed_since_last_check')
    op.drop_column('etl_schedule', 'target_watermark')
    op.drop_column('etl_schedule', 'source_watermark')
    op.drop_column('etl_schedule', 'last_trigger_type')
    op.drop_column('etl_schedule', 'cancellation_requested')
    op.drop_column('etl_schedule', 'current_execution_id')
    op.drop_column('etl_schedule', 'session_id')
    op.drop_column('etl_schedule', 'etl_type')
    op.alter_column('Mission_configurations', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_table('watchman_audit_log')
    op.drop_table('etl_execution_logs')
    op.drop_table('etl_execution_progress')
    op.drop_table('etabeta')
    op.drop_table('alphabeta')
    op.drop_index(op.f('ix_watchman_statistics_stat_date'), table_name='watchman_statistics')
    op.drop_table('watchman_statistics')
    # ### end Alembic commands ###
