"""Added new tables

Revision ID: 657b230b610b
Revises: a65a04270df2
Create Date: 2025-11-26 14:28:29.896531
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '657b230b610b'
down_revision: Union[str, Sequence[str], None] = 'a65a04270df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'etl_audit_log',
        sa.Column('log_id', sa.Uuid(), nullable=False),
        sa.Column('run_id', sa.Uuid(), nullable=False),
        sa.Column('component_id', sa.Uuid(), nullable=False),
        sa.Column('ship_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('nomenclature', sa.Text(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('rows_processed', sa.Integer(), nullable=False),
        sa.Column('rows_inserted', sa.Integer(), nullable=False),
        sa.Column('rows_updated', sa.Integer(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('error_details', sa.Text(), nullable=True),
        sa.Column('retry_attempt', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id']),
        sa.PrimaryKeyConstraint('log_id')
    )

    op.create_table(
        'etl_schedule',
        sa.Column('component_id', sa.Uuid(), nullable=False),
        sa.Column('frequency_minutes', sa.Integer(), nullable=False),
        sa.Column('last_run_time', sa.DateTime(), nullable=True),
        sa.Column('next_run_time', sa.DateTime(), nullable=True),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('max_retries', sa.Integer(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id']),
        sa.PrimaryKeyConstraint('component_id')
    )

    # Do NOT alter system_id — leave it nullable
    # op.alter_column('system_configuration', 'system_id',
    #            existing_type=mssql.UNIQUEIDENTIFIER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('etl_schedule')
    op.drop_table('etl_audit_log')
    # system_id left nullable
