"""Initial migration

Revision ID: 731385d0b21a
Revises: 
Create Date: 2026-03-10 14:06:08.659744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '731385d0b21a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ships',
    sa.Column('ship_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ship_category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ship_class', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ship_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ship_id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('inactivity_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('max_login_attempts', sa.Integer(), nullable=False),
    sa.Column('lockout_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('password_min_length', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('systems',
    sa.Column('system_id', sa.Uuid(), nullable=False),
    sa.Column('system_type', sa.Enum('PROPULSION', 'POWER_GENERATION', 'SUPPORT', 'FIRING', name='systemtype'), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('role', sa.Enum('SUPERUSER', 'ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('watchman_statistics',
    sa.Column('stat_id', sa.Uuid(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('total_checks', sa.Integer(), nullable=False),
    sa.Column('syncs_triggered', sa.Integer(), nullable=False),
    sa.Column('syncs_skipped', sa.Integer(), nullable=False),
    sa.Column('false_positives', sa.Integer(), nullable=False),
    sa.Column('avg_check_duration_ms', sa.Float(), nullable=True),
    sa.Column('total_time_saved_seconds', sa.Integer(), nullable=False),
    sa.Column('total_rows_synced', sa.Integer(), nullable=False),
    sa.Column('skip_rate_percent', sa.Float(), nullable=True),
    sa.Column('accuracy_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('stat_id')
    )
    op.create_index(op.f('ix_watchman_statistics_stat_date'), 'watchman_statistics', ['stat_date'], unique=False)
    op.create_table('Mission_configurations',
    sa.Column('config_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ship_id', sa.Uuid(), nullable=False),
    sa.Column('ship_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.ship_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('department_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('department_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('ship_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.ship_id'], ),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('system_configuration',
    sa.Column('component_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('system_id', sa.Uuid(), nullable=False),
    sa.Column('ship_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('CMMS_EquipmentCode', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_lmu', sa.Integer(), nullable=False),
    sa.Column('parent_name', sqlmodel.sql.sqltypes.AutoString(length=8000), nullable=True),
    sa.Column('nomenclature', sqlmodel.sql.sqltypes.AutoString(length=8000), nullable=True),
    sa.Column('etl', sa.Boolean(), nullable=True),
    sa.Column('RepairType', sa.Enum('repairable', 'replaceable', name='repairtypeenum'), nullable=True),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['system_configuration.component_id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.ship_id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.system_id'], ),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('EB_TTF_data',
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('f_s', sa.Enum('FAILURE', 'SUSPENSION', name='failurestatusenum'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EB_TTF_data_component_id'), 'EB_TTF_data', ['component_id'], unique=False)
    op.create_table('EB_actual_data',
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('interval_start_date', sa.Date(), nullable=False),
    sa.Column('interval_end_date', sa.Date(), nullable=False),
    sa.Column('f_s', sa.Enum('FAILURE', 'SUSPENSION', name='failurestatusenum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EB_actual_data_component_id'), 'EB_actual_data', ['component_id'], unique=False)
    op.create_table('EB_expert',
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('most_likely_life', sa.Float(), nullable=False),
    sa.Column('max_life', sa.Float(), nullable=False),
    sa.Column('min_life', sa.Float(), nullable=False),
    sa.Column('num_component_wo_failure', sa.Integer(), nullable=False),
    sa.Column('time_wo_failure', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EB_expert_component_id'), 'EB_expert', ['component_id'], unique=False)
    op.create_table('EB_interval_data',
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('installation_start_date', sa.Date(), nullable=False),
    sa.Column('installation_end_date', sa.Date(), nullable=False),
    sa.Column('removal_start_date', sa.Date(), nullable=False),
    sa.Column('removal_end_date', sa.Date(), nullable=False),
    sa.Column('f_s', sa.Enum('FAILURE', 'SUSPENSION', name='failurestatusenum'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EB_interval_data_component_id'), 'EB_interval_data', ['component_id'], unique=False)
    op.create_table('EB_nprd',
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EB_nprd_component_id'), 'EB_nprd', ['component_id'], unique=False)
    op.create_table('EB_oem',
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('life_estimate1_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('life_estimate1_val', sa.Float(), nullable=False),
    sa.Column('life_estimate2_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('life_estimate2_val', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EB_oem_component_id'), 'EB_oem', ['component_id'], unique=False)
    op.create_table('EB_oem_expert',
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('most_likely_life', sa.Float(), nullable=False),
    sa.Column('max_life', sa.Float(), nullable=False),
    sa.Column('min_life', sa.Float(), nullable=False),
    sa.Column('life_estimate_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('life_estimate_val', sa.Float(), nullable=True),
    sa.Column('num_component_wo_failure', sa.Integer(), nullable=False),
    sa.Column('time_wo_failure', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EB_oem_expert_component_id'), 'EB_oem_expert', ['component_id'], unique=False)
    op.create_table('EB_prob_failure',
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('p_time', sa.Float(), nullable=False),
    sa.Column('failure_p', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_EB_prob_failure_component_id'), 'EB_prob_failure', ['component_id'], unique=False)
    op.create_table('Overhaul_Readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('maintenance_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('defect_date', sa.Date(), nullable=False),
    sa.Column('cmms_running_age', sa.Float(), nullable=False),
    sa.Column('running_age', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Overhaul_Readings_id'), 'Overhaul_Readings', ['id'], unique=False)
    op.create_table('Overhaul_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('overhaul_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('total_overhaul_events', sa.Integer(), nullable=False),
    sa.Column('last_overhaul_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Overhaul_metadata_id'), 'Overhaul_metadata', ['id'], unique=False)
    op.create_table('alphabeta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_manager_maintenance_data',
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('maint_date', sa.Date(), nullable=True),
    sa.Column('maintenance_type', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('replaced_component_type', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('cannabalised_age', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('maintenance_duration', sa.Float(), nullable=True),
    sa.Column('failure_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_manager_maintenance_data_component_id'), 'data_manager_maintenance_data', ['component_id'], unique=False)
    op.create_table('etabeta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('eta', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etl_audit_log',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('ship_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('nomenclature', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('retry_attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('etl_execution_progress',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('job_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('current_step', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_table('etl_schedule',
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('etl_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('last_run_time', sa.DateTime(), nullable=True),
    sa.Column('next_run_time', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('current_execution_id', sa.Uuid(), nullable=True),
    sa.Column('cancellation_requested', sa.Boolean(), nullable=False),
    sa.Column('last_trigger_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('source_watermark', sa.DateTime(), nullable=True),
    sa.Column('target_watermark', sa.DateTime(), nullable=True),
    sa.Column('rows_changed_since_last_check', sa.Integer(), nullable=True),
    sa.Column('last_change_detected', sa.DateTime(), nullable=True),
    sa.Column('sync_risk_score', sa.Integer(), nullable=False),
    sa.Column('last_sync_start', sa.DateTime(), nullable=True),
    sa.Column('last_sync_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('component_id', 'etl_type')
    )
    op.create_table('failure_modes',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('failure_mode_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('failure_mode_id')
    )
    op.create_table('maintenance_configuration_data',
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('pm_applicable', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('can_be_replaced_by_ship_staff', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('is_system_param_recorded', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('maintenance_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_index(op.f('ix_maintenance_configuration_data_component_id'), 'maintenance_configuration_data', ['component_id'], unique=False)
    op.create_table('monthly_utilization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_date', sa.DateTime(), nullable=False),
    sa.Column('utlization', sa.Numeric(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rcm',
    sa.Column('rcm_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('decision_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('maintenance_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('rcm_id')
    )
    op.create_table('redundancy_data',
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('k', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('redundancy_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_parent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('redundancy_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('redundancy_id')
    )
    op.create_index(op.f('ix_redundancy_data_component_id'), 'redundancy_data', ['component_id'], unique=False)
    op.create_table('system_config_additional_info',
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('component_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('num_cycle_or_runtime', sa.Float(), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_config_additional_info_component_id'), 'system_config_additional_info', ['component_id'], unique=False)
    op.create_table('etl_execution_logs',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('log_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['etl_execution_progress.execution_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('sensor_metadata',
    sa.Column('sensor_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('P', sa.Float(), nullable=True),
    sa.Column('F', sa.Float(), nullable=True),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('failure_mode_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['failure_modes.failure_mode_id'], ),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_table('watchman_audit_log',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('check_timestamp', sa.DateTime(), nullable=False),
    sa.Column('needs_sync', sa.Boolean(), nullable=False),
    sa.Column('decision_reason', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('source_row_count', sa.Integer(), nullable=True),
    sa.Column('target_row_count', sa.Integer(), nullable=True),
    sa.Column('changed_rows_count', sa.Integer(), nullable=True),
    sa.Column('source_watermark', sa.DateTime(), nullable=True),
    sa.Column('check_duration_ms', sa.Integer(), nullable=True),
    sa.Column('job_queued', sa.Boolean(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['etl_execution_progress.execution_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('sensor_readings',
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('operating_hours', sa.Integer(), nullable=True),
    sa.Column('alert', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor_metadata.sensor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_readings')
    op.drop_table('watchman_audit_log')
    op.drop_table('sensor_metadata')
    op.drop_table('etl_execution_logs')
    op.drop_index(op.f('ix_system_config_additional_info_component_id'), table_name='system_config_additional_info')
    op.drop_table('system_config_additional_info')
    op.drop_index(op.f('ix_redundancy_data_component_id'), table_name='redundancy_data')
    op.drop_table('redundancy_data')
    op.drop_table('rcm')
    op.drop_table('monthly_utilization')
    op.drop_index(op.f('ix_maintenance_configuration_data_component_id'), table_name='maintenance_configuration_data')
    op.drop_table('maintenance_configuration_data')
    op.drop_table('failure_modes')
    op.drop_table('etl_schedule')
    op.drop_table('etl_execution_progress')
    op.drop_table('etl_audit_log')
    op.drop_table('etabeta')
    op.drop_index(op.f('ix_data_manager_maintenance_data_component_id'), table_name='data_manager_maintenance_data')
    op.drop_table('data_manager_maintenance_data')
    op.drop_table('alphabeta')
    op.drop_index(op.f('ix_Overhaul_metadata_id'), table_name='Overhaul_metadata')
    op.drop_table('Overhaul_metadata')
    op.drop_index(op.f('ix_Overhaul_Readings_id'), table_name='Overhaul_Readings')
    op.drop_table('Overhaul_Readings')
    op.drop_index(op.f('ix_EB_prob_failure_component_id'), table_name='EB_prob_failure')
    op.drop_table('EB_prob_failure')
    op.drop_index(op.f('ix_EB_oem_expert_component_id'), table_name='EB_oem_expert')
    op.drop_table('EB_oem_expert')
    op.drop_index(op.f('ix_EB_oem_component_id'), table_name='EB_oem')
    op.drop_table('EB_oem')
    op.drop_index(op.f('ix_EB_nprd_component_id'), table_name='EB_nprd')
    op.drop_table('EB_nprd')
    op.drop_index(op.f('ix_EB_interval_data_component_id'), table_name='EB_interval_data')
    op.drop_table('EB_interval_data')
    op.drop_index(op.f('ix_EB_expert_component_id'), table_name='EB_expert')
    op.drop_table('EB_expert')
    op.drop_index(op.f('ix_EB_actual_data_component_id'), table_name='EB_actual_data')
    op.drop_table('EB_actual_data')
    op.drop_index(op.f('ix_EB_TTF_data_component_id'), table_name='EB_TTF_data')
    op.drop_table('EB_TTF_data')
    op.drop_table('system_configuration')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('departments')
    op.drop_table('Mission_configurations')
    op.drop_index(op.f('ix_watchman_statistics_stat_date'), table_name='watchman_statistics')
    op.drop_table('watchman_statistics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('systems')
    op.drop_table('system_settings')
    op.drop_table('ships')
    # ### end Alembic commands ###
