"""Initial migration

Revision ID: 9c2c19c41161
Revises: 
Create Date: 2025-07-19 18:38:21.794623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c2c19c41161'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ships',
    sa.Column('ship_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ship_category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ship_class', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ship_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ship_id')
    )
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('role', sa.Enum('DEVELOPER_MODE', 'SHIP_HOD', 'SHIP_CO', 'FLEET_COMMAND_HQ', 'NHQ', 'ADMIN_INSMA', 'HANDHELD', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('departments',
    sa.Column('department_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('department_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('ship_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.ship_id'], ),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('system_configuration',
    sa.Column('component_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ship_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('CMMS_EquipmentCode', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_lmu', sa.Integer(), nullable=False),
    sa.Column('parent_name', sqlmodel.sql.sqltypes.AutoString(length=8000), nullable=True),
    sa.Column('nomenclature', sqlmodel.sql.sqltypes.AutoString(length=8000), nullable=True),
    sa.Column('etl', sa.Boolean(), nullable=True),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['system_configuration.component_id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.ship_id'], ),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('alphabeta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alphabeta_id'), 'alphabeta', ['id'], unique=False)
    op.create_table('etabeta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('eta', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etabeta_id'), 'etabeta', ['id'], unique=False)
    op.create_table('failure_modes',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('failure_mode_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('failure_mode_id')
    )
    op.create_table('monthly_utilization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_date', sa.DateTime(), nullable=False),
    sa.Column('utlization', sa.Numeric(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_metadata',
    sa.Column('sensor_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('P', sa.Float(), nullable=True),
    sa.Column('F', sa.Float(), nullable=True),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('failure_mode_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['failure_modes.failure_mode_id'], ),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_table('sensor_readings',
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('operating_hours', sa.Integer(), nullable=True),
    sa.Column('alert', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['system_configuration.component_id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor_metadata.sensor_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_readings')
    op.drop_table('sensor_metadata')
    op.drop_table('monthly_utilization')
    op.drop_table('failure_modes')
    op.drop_index(op.f('ix_etabeta_id'), table_name='etabeta')
    op.drop_table('etabeta')
    op.drop_index(op.f('ix_alphabeta_id'), table_name='alphabeta')
    op.drop_table('alphabeta')
    op.drop_table('system_configuration')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('departments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ships')
    # ### end Alembic commands ###
