"""removed ship id from system table

Revision ID: a65a04270df2
Revises: fe199ed4b651
Create Date: 2025-07-30 15:23:56.749266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'a65a04270df2'
down_revision: Union[str, Sequence[str], None] = 'fe199ed4b651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_configuration', 'system_id',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               nullable=True)
    
    # Use raw SQL to drop all foreign key constraints referencing ship_id in systems table
    op.execute(sa.text("""
        DECLARE @sql NVARCHAR(MAX) = ''
        SELECT @sql = @sql + 'ALTER TABLE systems DROP CONSTRAINT ' + QUOTENAME(name) + ';' + CHAR(13)
        FROM sys.foreign_keys 
        WHERE parent_object_id = OBJECT_ID('systems') 
        AND referenced_object_id = OBJECT_ID('ships')
        AND EXISTS (
            SELECT 1 FROM sys.foreign_key_columns fkc
            JOIN sys.columns c ON fkc.parent_object_id = c.object_id AND fkc.parent_column_id = c.column_id
            WHERE fkc.constraint_object_id = sys.foreign_keys.object_id
            AND c.name = 'ship_id'
        )
        
        EXEC sp_executesql @sql
    """))
    
    # Now drop the column
    op.drop_column('systems', 'ship_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('ship_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('FK__systems__ship_id__498EEC8D'), 'systems', 'ships', ['ship_id'], ['ship_id'])
    op.alter_column('system_configuration', 'system_id',
               existing_type=mssql.UNIQUEIDENTIFIER(),
               nullable=True)
    # ### end Alembic commands ###
