"""Added mission config table

Revision ID: e17c8ad27b4f
Revises: 657b230b610b
Create Date: 2025-11-26 20:47:50.138145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'e17c8ad27b4f'
down_revision: Union[str, Sequence[str], None] = '657b230b610b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Mission_configurations',
    sa.Column('config_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Mission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Mission_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.String(255), nullable=False),  # Fixed: specific length instead of AutoString
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Mission_configurations')
    # ### end Alembic commands ###