"""Add systems table and system_id to system_configuration

Revision ID: fe199ed4b651
Revises: 9c2c19c41161
Create Date: 2025-07-30 15:09:22.356949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe199ed4b651'
down_revision: Union[str, Sequence[str], None] = '9c2c19c41161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('system_id', sa.Uuid(), nullable=False),
    sa.Column('system_type', sa.Enum('PROPULSION', 'POWER_GENERATION', 'SUPPORT', 'FIRING', name='systemtype'), nullable=False),
    sa.Column('ship_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.ship_id'], ),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.add_column('system_configuration', sa.Column('system_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'system_configuration', 'systems', ['system_id'], ['system_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_configuration', type_='foreignkey')
    op.drop_column('system_configuration', 'system_id')
    op.drop_table('systems')
    # ### end Alembic commands ###
